### ISSUE TITLE
[Feature Request] Hide everything from players

### ISSUE THREAD

**Issue by NdranC** [theripper93/Maxwell-s-Manual-of-Malicious-Maladies#1]
I think it would be useful to have a configuration toggle for automated damage prompts to only show/warn DMs, (it currently only shows to the owner of the token) as well as making all chat messages related to this hidden from the players. This would allow more narrative control for DMs as well as prevent (possible) sneaky players that could close the dialog prompt and not reveal they took enough damage for a wound.

Thanks for your time.

**Comment by theripper93** [comment]
Sorry, forgot to add this to this repo - https://github.com/theripper93/Levels/blob/v9/ISSUES.md
