### ISSUE TITLE
Spell critical hits not triggering rolltable

### ISSUE THREAD

**Issue by UmbraZeal** [theripper93/Maxwell-s-Manual-of-Malicious-Maladies#3]
Spell critical hits aren't triggering the roll tables for their damage type, no pop up comes up for it either.

Foundry version - v11.315
DnD5e - v2.4.1
MMoMM - v1.2.2

**Comment by theripper93** [comment]
This only works when using midiqol

**Comment by theripper93** [comment]
Also, if that didn’t answer your question and you wish to further investigate this, follow the complete bug report procedure and reopen the issue

Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
