### ISSUE TITLE
A roll request is sent to the player without notifying the GM. Request to have it sent to chat instead.

### ISSUE THREAD

**Issue by stonedtroll** [theripper93/Maxwell-s-Manual-of-Malicious-Maladies#4]
Currently, when an event triggers a roll dialogue, it is sent to the player only. This is a problem as the player might be confused by it and click cancel. Is it possible to send the request to chat or have the request sent to the GM on the player's behalf instead?

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
